config/routes.rb
YFA::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => "users/registrations"}
resources :users
resources :interests
resources :projects
resources :roles
resources :auditions

root 'static_pages#home'

  get "users/new"

  match '/screenings', to: 'static_pages#screenings', via: 'get'
  
  match '/screenings/:id', to: 'static_pages#show', via: 'get'

  match '/search', to: 'projects#search', via: 'get'
  
  match '/search', to: 'projects#search', via: 'post'

  match 'users/:id/edit', to: 'users#edit', via: 'get'

  match 'users/:id', to: 'users#show', via: 'get'

  match '/projects/:id/auditions', to: 'auditions#show', via: 'get'

  match '/edit', to: 'users#edit', via: 'get'

  match '/logout', to: 'static_pages#logout', via: 'get'

  get "static_pages/new"
  get "static_pages/create"
  
  get "users/create"
  get "users/update"
  get "users/edit"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  

  # validates :name, presence: true, length: { maximum: 50 }, :on => :update #these are simply methods
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[yale]+\.[edu]+\z/i
  # validates :email, presence: true, 
  #           format: { with: VALID_EMAIL_REGEX }, 
  #           uniqueness: { case_sensitive: false }, :on => :update
  # has_secure_password
  # validates :password, length: { minimum: 6 }
 
  # Associations
  has_many :roles
  has_many :projects, through: :roles
  has_one :interest
  has_many :auditions
  mount_uploader :image, ImageUploader

  accepts_nested_attributes_for :interest
 
 
    
  # Accessors 
  
  
 

 
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def new

  	super
    	@user = User.new
    	# @interest = @me.build_interest

  end

  def create
    super
     	@user = User.create(me_params)
      # using one of the handy has_one associations to directly correlate the two objects
   	 	# @interest = @me.create_interest(interest_params)
   	 	
  end

private

  		def me_params
  			params.require(:user).permit( :name, :fname, :lname, :college, :year, 
                                      :email, :college, :bio, :netid, :image, :password, :password_confirmation )
  		end

      def interest_params
        params.require(:interest).permit(:acting, :directing, :camerawork, :cinematography, :costumes, :sound, :editing)
      end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index 
  end

  def new #will need landing page  
    # if @me.email && @me.college && @me.year
    #   redirect_to user_path(@me.id)
    # end
    @user = User.new
    @interest = @user.build_interest

  end

  def create
    @user = User.create(me_params)
      # using one of the handy has_one associations to directly correlate the two objects
    @interest = @user.create_interest(interest_params)
  end

  def edit #edit that particular user
    @me = current_user
    @interest = @me.create_interest
  end

  def update
    @interest = current_user.interest
    @interest.update(interest_params)
    current_user.update(me_params)
    redirect_to user_path
  end

  def search

  end

  def show
    @user = User.find(params[:id])
    @interest = @user.interest
    @attributes = Interest.column_names
    @attributes.reject! {|item| item =~ /id|user_id|updated_at|created_at/ }
  end


  	private

  		def me_params
  			params.require(:user).permit( :name, :fname, :lname, :college, :year, 
                                      :email, :college, :bio, :netid, :image )
  		end

      def interest_params
        params.require(:interest).permit(:acting, :directing, :camerawork, :cinematography, :costumes, :sound, :editing)
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class = "pure-g">

    <div class = "pure-u-1 container">
        <h1> EDIT PROFILE </h1>

      

		<div class = "pure-form">
	
			<%= form_for(@me) do |f| %>

			<p> 
			<%= f.label "YOUR HEADSHOT" %> <br>
			<%= f.file_field :image %> 
			</p>

            <p> 
            <%= f.label "CHANGE NAME" %> <br>
            <%= f.text_field :name %> 
            </p>

            <p> 
            <%= f.label "CHANGE NICKNAME" %> <br>
            <%= f.text_field :fname %> 
            </p>

            <p> 
            <%= f.label "CHANGE EMAIL" %> <br>
            <%= f.text_field :email %> 
            </p>

			<p> 
			<%= f.label "BIO" %> <br>
			<%= f.text_area :bio %> 
			</p>

			<h3>What are your interests?</h3>

            <%= f.hidden_field :id, value: @me %>
            <!-- TAKE A LOOK AT THIS ^^ -->

            <%= fields_for(@me.interest) do |ff| %>
                <p><%= ff.label "acting" %>
                <%= ff.check_box :acting %></p>

                <p><%= ff.label "directing" %>
                <%= ff.check_box :directing %></p>


                <p><%= ff.label "editing" %>
                <%= ff.check_box :editing %></p>


                <p><%= ff.label "costumes" %>
                <%= ff.check_box :costumes %></p>


                <p><%= ff.label "cinematography" %>
                <%= ff.check_box :cinematography %></p>


                <p><%= ff.label "camerawork" %>
                <%= ff.check_box :camerawork %></p>


                <p><%= ff.label "sound" %>
                <%= ff.check_box :sound %></p>

                <%= f.submit "Save Changes", class: "pure-button" %>
            <% end %>
        <% end %>


        </div>
    </div>
</div>

app/views/users/index.html.erb
	<h1> All Filmmakers </h1>


<div class = "pure-g">
	<div class = "pure-u-1 container">
		
		<% User.all.each do |u| %>

			<div class = "pure-u-1-2 user_list">
				<div class="user_thumb">
					<%= image_tag u.image_url(:tiny_avatar).to_s %>
				</div>
				<%= link_to u.name, user_path(u.id)%>
			</div>

		<% end %>

	</div>
</div>

app/views/users/new.html.erb
<div class="pure-g">
  <div class="pure-u-1 container">
    
<h1>Sign up</h1>
   <div class = "pure-form">

      <%= form_for(@me) do |f| %>
        

          <%= f.label :Full_Name %>
          <p><%= f.text_field :name %></p>

          <%= f.label :Nick_Name %>
          <p><%= f.text_field :fname %></p>

          <%= f.label :Yale_email %>
          <p><%= f.text_field :email %></p>

          <%= f.label :college %>
          <p><%= f.text_field :college %></p>

          <%= f.label :year %>
          <p><%= f.text_field :year %></p>

          <%= fields_for(@interest) do |ff| %>
            <%= ff.hidden_field :acting, value: '0' %>
            <%= ff.hidden_field :directing, value: '0' %>
            <%= ff.hidden_field :editing, value: '0' %>
            <%= ff.hidden_field :camerawork, value: '0' %>
            <%= ff.hidden_field :costumes, value: '0' %>
            <%= ff.hidden_field :cinematography, value: '0' %>
            <%= ff.hidden_field :sound, value: '0' %>
          <% end %>

          <%= f.submit "Save Changes", class: "pure-button" %>
        
        <% end %>

  </div>


  </div>
</div>

app/views/users/show.html.erb
<div class = "pure-g">

    <div class = "container">
            <div class = "pure-u-1-2 left-column">
                <h1 class= "left_align"><% if @user == current_user %> Hello, <% end %> <%= @user.fname%> </h1> 
                <div class = "profile_image">
                    <%= image_tag @user.image_url(:thumb).to_s %>
                </div>
                <p><%= @user.college %> </p>
                <p><%= @user.year %> </p>
                <p><%= mail_to @user.email, "Email me!" %></p>

            <% if can? :update, @user %>
                <div class = "section authorized">
                    <p> <%= link_to "Edit your information, friend!", edit_user_path(current_user) %></p>
                </div>


                    <div class="spacing_button">
                        <%= link_to "Create a New Project", new_project_path, class: "pure-button" %>
                    </div>

            <% end %>

            </div>
            
            <div class = "pure-u-1-2 right-column">

                <% if can? :manage, Project, :producer => current_user %>
                <div class = "section authorized" id= "activity">
                        ACTIVITY ON YOUR PROJECTS</br>

                            <% myprojects = @user.projects %>

                            <% myprojects.each do |p| %>
                                    <% auditions = p.auditions %>
                                <% auditions.each do |a| %>

                                    <% if a.role_id == nil && a.user_id != nil %>
                                        <p>    <%= link_to a.user_name, user_path(a.user_id) %> 
                                            <%= " has an audition on #{ a.when.strftime("%B %d at %l%p") } 
                                            for " %>
                                            <%= link_to p.title, "/projects/#{p.id}/auditions" %>
                                        </p>
                                    <% elsif a.role_id != nil %>
                                        <% crew_position = Role.find(a.role_id).title %>
                                        <% crew_user = User.find(a.user_id).fname %>
                                        <p>    <%= link_to crew_user, user_path(a.user_id) %>
                                            <%= " wants to be your #{crew_position} for " %>
                                            <%= p.title %>
                                        </p>                    
                                    <% end %>

                                <% end %>
                            <% end %>
                </div>
                <% end %>



                <h2>BIO</h2>
                <%= @user.bio %> <br>
                
                <div class="section">
                    <h2>Interests</h2>
                    <% if @user.interest != nil %>
                    <% @user.interest.attributes.each_pair do |name, value| %>
                        <% if value == "1" %>
                            <div class="interest_block pure-u-1-3">
                                <p><%= name %></p>
                            </div>
                        
                        <% end %>
                    <% end %>
                    <% end %>
                </div>

                <div class="section">
                    <h2>Filmography</h2>

                    <% @user.projects.distinct.each do |project| %>
                        <% my_roles = project.roles.where(user_id: @user.id) %>

                        <p><%= link_to project.title, project_path(project.id)%> |

                            <% array = [] %>
                            <% my_roles.each do |r| %>
                                <% if r.title == nil %>
                                    <% array.push("Producer")%>
                                <% else %>
                                    <% array.push(r.title) %>
                                <% end %> 
                            <% end %>

                            <%= array.join(", ") %>
                        </p>

                    <% end %>
                </div>
                
            </div>
    </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>