config/routes.rb
YFA::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => "users/registrations"}
resources :users
resources :interests
resources :projects
resources :roles
resources :auditions

root 'static_pages#home'

  get "users/new"

  match '/screenings', to: 'static_pages#screenings', via: 'get'
  
  match '/screenings/:id', to: 'static_pages#show', via: 'get'

  match '/search', to: 'projects#search', via: 'get'
  
  match '/search', to: 'projects#search', via: 'post'

  match 'users/:id/edit', to: 'users#edit', via: 'get'

  match 'users/:id', to: 'users#show', via: 'get'

  match '/projects/:id/auditions', to: 'auditions#show', via: 'get'

  match '/edit', to: 'users#edit', via: 'get'

  match '/logout', to: 'static_pages#logout', via: 'get'

  get "static_pages/new"
  get "static_pages/create"
  
  get "users/create"
  get "users/update"
  get "users/edit"

end

app/models/project.rb
class Project < ActiveRecord::Base
	

	scope :find_project, -> (lambda) { where("title like ?", "%#{lambda}%")}

	has_many :roles
	has_many :users, through: :roles
	has_many :auditions
	mount_uploader :image, ImageUploader

	accepts_nested_attributes_for :auditions, :reject_if => :all_blank, :allow_destroy => true

	auto_html_for :video do
	    html_escape
	    image
	    youtube(:autoplay => false)
	    link :target => "_blank", :rel => "nofollow"
	    simple_format
  	end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		
	end

	def search #must search with both first and last names currently (search bar). Look into inter-model searching
		@movie = Project.where(nil) #creates an anonymous scope
		@movie = @movie.find_project(params[:search]) if params[:search].present?
		@person = User.where(name: params[:search]) if params[:search].present?
	end

	def new
		
		@project = current_user.projects.new
	end

	def create

		@project = current_user.projects.create(project_params)
		redirect_to project_path(@project)
	end

	def show #lots of variables available for refactoring. 
		
		@project = Project.find(params[:id])
		@producer_id = Role.find_by(project_id: @project.id).user_id
		@producer = User.find_by(id: @producer_id)
  		@role = @project.roles.build
  		@audition = @project.auditions.build

		if can? :manage, Project, :producer => current_user
			@project = current_user.projects.find(params[:id])	
  			@role = @project.roles.build
  		end
		#NOTE: find_by(params[:id]) doesn't work! @me.projects.find_by(id: params[:id]) OR @me.projects.find(params[:id]) are equivalent syntax.
	end

	def edit
		@project = current_user.projects.find(params[:id]) #refactor: create application helper for @project to call before controller functions
		
	end

	def update 
		@project = current_user.projects.find(params[:id])
		@project.update(project_params)
		redirect_to project_path(@project)
	end

	def destroy
		@project = current_user.projects.find(params[:id])
		@project.destroy
		redirect_to user_path(current_user)
	end

  private

	def project_params
        params.require(:project).permit(:title, :genre, :description, :dates, :producer,
        					 :location, :image, :remote_image_url, :video, :video_html,
        					 auditions_attributes: [:id, :when, :project_id, :user_id,
        					 :user_name, :role_id, :_destroy])
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<div class = "pure-g">

	<div class = "pure-u-1 container">
		<h1> Edit "<%= @project.title %>" project </h1>

		<div class = "pure-form">

			<%= form_for(@project) do |f| %>
				<%= f.hidden_field :id, value: current_user %>

				<%= f.text_field :title, :placeholder => "Project title", :class => "pure-input" %>

				<%= f.label "Genre: "%>
				<%= f.select :genre, options_for_select([["Other", "Other"], ["Comedy", "Comedy"], ["Documentary", "Documentary"], ["Drama", "Drama"] ], :class => "fields") %>

				<p> <%= f.text_area :description, :placeholder => "Describe the project", :class => "pure-input" %> </p>

				<p> <%= f.text_field :dates, :placeholder => "Dates", :class => "pure-input" %> </p>

				<p> <%= f.text_field :location, :placeholder => "Location", :class => "pure-input" %> </p>

				<p> <%= f.label "Upload image" %> <br>
				 	<%= f.file_field :image %> </p>

				<p> <%= f.label :remote_image_url, "or image url" %> <br>
				 	<%= f.text_field :remote_image_url %> </p>

				<p> <%= f.label "Link to video" %> <br>
				 	<%= f.text_field :video %> </p>

				<p> Coming Soon: Script uploads! </p>

			<%= f.submit "Save changes", class: "pure-button" %>
			<% end %>


		</div>

	</div>
</div>

app/views/projects/index.html.erb
<h1> Projects </h1>

<div class = "pure-g">
<div class = "pure-u-1 projects_container">


	<% Project.all.each do |p| %>

		<div class = "pure-u-1-3 project">
			<%= image_tag p.image_url(:thumb).to_s %>

			<div class = "project_text">
				<h4><%= link_to p.title, project_path(p.id)%></h4>
				<p> <%= p.dates %> </p>
			</div>

			<div class= "genre" > 
				<%= p.genre %> 
			</div>
		</div>
	<% end %>

</div>
</div>

app/views/projects/new.html.erb
<div class = "pure-g">

	<div class = "pure-u-1 container">
		<h1> Create a New Project </h1>

		<div class = "pure-form">
	
			<%= form_for(@project) do |f| %>
				<%= f.hidden_field :user_id, value: current_user %>

				<%= f.text_field :title, :placeholder => "Project title", :class => "pure-input" %>

				<%= f.label "Genre: "%>
				<%= f.select :genre, options_for_select([ ["Comedy", "Comedy"], ["Documentary", "Documentary"], ["Drama", "Drama"], ["Silent", "Silent"], ["Adult", "Adult"], ["Sci-Fi", "Sci-Fi"], ["Animation", "Animation"], ["Alternative, Alternative"], ["Other", "Other"] ], :class => "fields") %>

				<p> <%= f.text_area :description, :placeholder => "Describe the project", :class => "pure-input" %> </p>

				<p> <%= f.text_field :dates, :placeholder => "Dates", :class => "pure-input" %> </p>

				<p> <%= f.text_field :location, :placeholder => "Location", :class => "pure-input" %> </p>

				<p> <%= f.label "Upload image" %> <br>
				 	<%= f.file_field :image %> </p>

				<p> <%= f.label :remote_image_url, "or image url" %> <br>
				 	<%= f.text_field :remote_image_url %> </p>

				<p> <%= f.label "Link to video" %> <br>
				 	<%= f.text_field :video %> </p>

				<p> Coming Soon: Upload your script! </p>

			<%= f.submit "Create Project", class: "pure-button" %>
			<% end %>


		</div>

	</div>
</div>

app/views/projects/search.html.erb
<div class = "pure-g">
	<div class = "pure-u-1 container user_list">
		<% @movie.each do |f| %>

			<p><%= link_to f.title, project_path(f.id) %></p>

		<% end %>


		<% @person.each do |f| %>

			<p><%= link_to f.name, user_path(f.id) %></p>

		<% end %>

		
	</div>
</div>

app/views/projects/show.html.erb
<div class = "pure-g">
	<div class = "container">
		<div class = "pure-u-1 title_bar">

			<h1 class = "project_title"> <%= @project.title %> </h1>
			<p class= "genre"> <%= @project.genre %></p>
			

		</div>
	</div>
</div>

<div class = "pure-g">

	<div class = "container">
			<div class = "pure-u-1-2 left-column">

				<div class = "project_image" >
					<%= image_tag @project.image_url.to_s %>
				</div>

				<div class="project_description">
					<p><b>DESCRIPTION:</b> <%= @project.description %> </p>
					<p><b>Dates:</b> <%= @project.dates %></p>
					<p><b>Location:</b> <%= @project.location %></p>
					<p><b>Producer:</b> <%= @producer.name %></p>
				</div>

					<% if can? :manage, Project %>
				<div class = "section authorized">
					<%= link_to "Edit this project", edit_project_path(@project) %> | 
					<%= link_to "Delete this project", @project, method: :delete, 
																		data: { confirm: "Are you sure you want to delete this project?"},
																		title: @project.title %>

				</div>
				<% end %>

				<% if can? :manage, Project %>
							<div class = "section authorized">
								<p> ADD ROLES </p>

								<%= form_for(@role) do |f| %>
									<%= f.text_field :title, placeholder: "Role title" %>
									<%= f.hidden_field :id, value: @project.id %>
									<br>
									<%= f.radio_button :cast, true %>
									<b><%= f.label "Cast?" %></b>
									or
									<%= f.radio_button :cast, false %>
									<b><%= f.label "Crew?" %></b>
									<%= f.submit "Add role", class: "pure-button" %>
								<% end %>
							</div>

							<div class = "section authorized">
								<p> ADD AUDITIONS </p>
								<%= link_to "Add audition slots", :controller => "auditions", :action => "new", :project => @project.id %>

								<p><%= link_to "View auditions for #{@project.title}", "/projects/#{@project.id}/auditions" %></p>
							</div>
							<% end %>
				
			</div>

			<div class = "pure-u-1-2 right-column">
				<div >
				<h2> Cast </h2>

					<% @project.roles.each do |r| %>

						<p>

						<% if r.cast == true %>
							<%= r.title %><span>  |  </span>

								<% if r.user_id == nil %>
								<i>uncast</i>
								<% else %>
								<% @user = User.find(r.user_id) %> <%= @user.name %>
								<% end %>

						<% if can? :manage, Project %>
						<div class = "authorized">
								<% auditions = @project.auditions %>
								<% array = [] %>

								<% auditioners = auditions.each {|a| array.push( [a.user_name, a.user_id])} %>
								
								<%= form_for(r) do |f| %>
									<%= f.label "Choose an actor" %>
									<%= f.select :user_id, options_for_select(array) %>
									<%= f.submit "Cast!", class: "pure-button" %>
								<% end %>
						</div>
						<% end %>

						<% end %> </p>
					<% end %>


						<% if user_signed_in? %>

								<%= link_to "Sign up for auditions!", "/projects/#{@project.id}/auditions", class: "pure-button" %>
						<% end %>
				</div>	
						

				<div class = "section">
				<h2> Crew </h2>
					<% @project.roles.each do |r| %>

						<p>
						<% if r.cast == false %>
							<%= r.title %> <span>  |  </span>

								<% if r.user_id == nil %>
									<i>needed</i>
								<% else %>
									<% @user = User.find(r.user_id) %> <%= @user.name %>
								<% end %>
							

							<% if can? :manage, Project %>
							<div class = "authorized">
								<% choose_crew = @project.auditions.where(:when => nil) %>
								<% choose_crew_array = [] %>
								<% choose_crew.each {|c| choose_crew_array.push( [User.find(c.user_id).fname, c.user_id])} %>
								
								<%= form_for(r) do |f| %>
									<%= f.label "Assign a crewmember" %>
									<%= f.select :user_id, options_for_select(choose_crew_array) %>
									<%= f.submit "Hire!", class: "pure-button" %>
								<% end %>
							</div>
							<% end %>

						<% end %> </p>
					<% end %>

							<% if user_signed_in? %>

								<% crew_roles = @project.roles.where(cast: false) %>
								<% crew_role_array = [] %>

								<% applicants = crew_roles.each {|r| crew_role_array.push( [r.title, r.id] )} %>

								<%= form_for(@audition) do |f| %>
									<%= f.hidden_field :project_id, value: @project.id %>
									<%= f.hidden_field :user_id, value: current_user %>
									<%= f.select :role_id, options_for_select(crew_role_array) %>
									<%= f.submit "Join us!", class: "pure-button" %>
								<% end %>

							<% end %>

				</div>

							
							
			</div>
		</div>
</div>