config/routes.rb
YFA::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => "users/registrations"}
resources :users
resources :interests
resources :projects
resources :roles
resources :auditions

root 'static_pages#home'

  get "users/new"

  match '/screenings', to: 'static_pages#screenings', via: 'get'
  
  match '/screenings/:id', to: 'static_pages#show', via: 'get'

  match '/search', to: 'projects#search', via: 'get'
  
  match '/search', to: 'projects#search', via: 'post'

  match 'users/:id/edit', to: 'users#edit', via: 'get'

  match 'users/:id', to: 'users#show', via: 'get'

  match '/projects/:id/auditions', to: 'auditions#show', via: 'get'

  match '/edit', to: 'users#edit', via: 'get'

  match '/logout', to: 'static_pages#logout', via: 'get'

  get "static_pages/new"
  get "static_pages/create"
  
  get "users/create"
  get "users/update"
  get "users/edit"

end

app/views/layouts/_header.html.erb
<div class = "pure-g"> 
	
	<div class = "pure-u-1 pure-menu pure-menu-open pure-menu-horizontal" id="menu">
		<ul id="std-menu-items">
			<li><a href="/">YFA </a> </li>
			<li> <%= link_to "Screenings", screenings_path %> </li>
			
			<% if !user_signed_in? %>
			<li> <%= link_to "Log In", new_user_session_path %> </li> <%# must direct this to a different path %>
			
			<% elsif user_signed_in? %>
			<li> <%= link_to "Projects", projects_path %></li>
			<li> <%= link_to "Filmmakers", users_path %> </li>
			<li> <%= link_to "Profile", user_path(current_user) %></li>

			<% end %>
			
			<li> 
				  <%= form_tag("/search", method: "get") do %>
				  <%= text_field_tag(:search) %>
				  <%= submit_tag("Search", class: "pure-button") %>
				  <% end %> 
			</li>
			<% if user_signed_in? %>
			<li> <%= link_to "Log out", destroy_user_session_path, :method => :delete  %> </li>

		<%# TODO: ADD ADMIN-SPECIFIC BUTTON TO ALLOW WEBMASTER MANAGERIAL CONTROL %>

			<% end %>
		</ul>
	</div>

<script>
YUI({
    classNamePrefix: 'pure'
}).use('gallery-sm-menu', function (Y) {

    var horizontalMenu = new Y.Menu({
        container         : '#menu',
        sourceNode        : '#std-menu-items',
        orientation       : 'horizontal',
        hideOnOutsideClick: false,
        hideOnClick       : false
    });

    horizontalMenu.render();
    horizontalMenu.show();

});
</script>



</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        
          <%= value %>
       
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>YFA</title>
  <link href='//fonts.googleapis.com/css?family=Josefin+Sans:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700' rel='stylesheet' type='text/css'>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  
  <link rel="stylesheet" href="/pure-min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', :cocoon, 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
<body>

	<%= render 'layouts/header' %>
	
	 <div class="container">
	
		<%= render 'layouts/messages' %>

		<%= yield %>
	<%= render 'layouts/footer' %>
	</div>



</body>
</html>